### ISSUE TITLE
Enable automated testing

### ISSUE THREAD

**Issue by Ichimonji10** [Ichimonji10/killjoy#7]
Automated testing should be performed for commits to the master branch, and pull requests. Automated testing for other branches could be nice too, but it's not essential.

I've used [Travis CI](https://travis-ci.org/) for automated testing in the past, and been happy. I'm not set on them, though.

When doing this, make sure to fill out the `[badges]` section in `Cargo.toml`. For more on that, see documentation for [the manifest format](https://doc.rust-lang.org/cargo/reference/manifest.html). Also, err on the side of being strict. Here's some checks that should be able to produce failures:

```bash
cargo check
cargo test
cargo fmt
cargo clippy
cargo doc
```

**Comment by cshlatz** [comment]
TravisCI: Check out PR #8
